server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: helloim-message
  redis:
    host: ${REDIS_ADDR:127.0.0.1}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/helloim0?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true}
    type: com.zaxxer.hikari.HikariDataSource
dubbo:
  application:
    name: helloim-message
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200
    port: 28805


mybatis:
  mapper-locations: classpath:mapper/*.xml

im:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      max-inflight-requests-per-connection: 1
      retries: 2
      batch-size: 1000
      buffer-memory: 3000000
      linger-ms: 10
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-records: 10
      group-id: helloim-message
      enable-autocommit: false
      auto-offset-reset: latest
