server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: helloim-dispatch
  redis:
    host: ${REDIS_ADDR:127.0.0.1}
dubbo:
  application:
    name: helloim-dispatch
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200
    port: 28801

im:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      max-inflight-requests-per-connection: 1
      retries: 2
      batch-size: 1000
      buffer-memory: 3000000
      linger-ms: 10
  downmsgsvc:
    keepalive-time-second: 10 # keeplive的间隔时间
    keepalive-timeout-second: 1 # keeplive的超时时间