logging:
  level:
    root: info
im:
  gate:
    protocol: ${PROTOCOL:tcp}
    port: ${GATE_PORT:9300}
    max-frame-size: 8192
    read-timeout-seconds: 630
    core-size: 200
    max-pool-size: 200
    queue-size: 20000