server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: helloim-gateway
dubbo:
  application:
    name: helloim-gateway
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200
    port: 28802

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics