server:
  port: 8085

spring:
  profiles:
    active: dev
  application:
    name: helloim-delivery
  redis:
    host: ${REDIS_ADDR:127.0.0.1}
dubbo:
  application:
    name: helloim-delivery
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200
    port: 28809

im:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-records: 10
      group-id: helloim-delivery
      enable-autocommit: false
      auto-offset-reset: latest
  downmsgsvc:
    keepalive-time-second: 10 # keeplive的间隔时间
    keepalive-timeout-second: 1 # keeplive的超时时间

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        prometheus: metrics